### ISSUE TITLE
AU Replication Stopped 3 days ago

### ISSUE THREAD

**Issue by ahhughes** [osm-fr/infrastructure#335] opened 2021-11-22 05:23 UTC
Hi All, 

Sorry to say, it looks like replication in Australia stopped on Friday.

http://download.openstreetmap.fr/replication/oceania/australia/minute/state.txt

Thank you

**Comment by jocelynj** [comment] 2021-11-22 20:03
There was an issue in diff generation, caused by a very big relation (European Union without overseas territories). I've fixed the issue, and generation is now progressing: http://munin.openstreetmap.fr/osm14.openstreetmap.fr/download.vm.openstreetmap.fr/osm_replication_lag_osmbin.html

**Comment by jocelynj** [comment] 2021-11-27 15:19
Issue is now fixed.

**Closed by jocelynj** 2021-11-27 15:19 UTC
